# Dependencies
markdown:           redcarpet
redcarpet:
  extensions:       ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
highlighter:        pygments

#github settings
baseurl:            
assetsurl:          /assets
jsurl:              /assets/js
cssurl:             /assets/css
imgurl:             /assets/img

gem:

# Permalinks
permalink:          pretty

#Server
# host:               127.0.0.1
# port:               4000
# baseurl:
# url:                http://127.0.0.1:4000
# encoding:           UTF-8


# the excluded directoies
exclude:            []

# site information
info:
  site_name:        HCC-Demo

meta:
  description:      "Hsin Chu gov official website demo"
  keywords:         ["hcc", 'demo']
  author:           "Finn Yeh"

# multiple language
lang:          ["en", "zh-tw", "zh-cn", "jp"]


# analytics account information, remember to change this.
analytics:
  google:
    account:
